# Generated by Django 2.0 on 2018-02-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_equipos_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Personas'),
        ),
    ]
