# Generated by Django 2.0 on 2018-02-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20180201_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personas1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ManyToManyField(to='inventario.Equipos1')),
            ],
        ),
    ]
