# Generated by Django 2.0 on 2018-02-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20180223_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas1',
            name='equipos',
            field=models.ManyToManyField(to='inventario.Equipos1'),
        ),
        migrations.RemoveField(
            model_name='personas1',
            name='nombre',
        ),
        migrations.AddField(
            model_name='personas1',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
